@Wrok.Identity.Api_HostAddress = https://wrok-gateway.blueflower-e984251a.eastus2.azurecontainerapps.io/identity

### Register
POST {{Wrok.Identity.Api_HostAddress}}/auth/register/
Accept: application/json
Content-Type: application/json

{
  "email":"test@test.com",
  "password":"Test1234*",
  "fullname":"Test 1",
  "tenantName":"TestTenant1"
}

### Login
POST {{Wrok.Identity.Api_HostAddress}}/auth/login/
Accept: application/json
Content-Type: application/json

{
  "email":"test2@test.com",
  "password":"Test1234*"
}

### Refresh Token
POST {{Wrok.Identity.Api_HostAddress}}/auth/refresh-token/
Accept: application/json
Content-Type: application/json

{
  "token":""
}