@Wrok.Identity.Api_HostAddress = https://localhost:7010

### Register
POST {{Wrok.Identity.Api_HostAddress}}/auth/register/
Accept: application/json
Content-Type: application/json

{
  "email":"test25test.com",
  "password":"Test1234",
  "fullname":"",
  "tenantName":"TestTenant2"
}

### Login
POST {{Wrok.Identity.Api_HostAddress}}/auth/login/
Accept: application/json
Content-Type: application/json

{
  "email":"test2@test.com",
  "password":"Test1234*"
}

### Refresh Token
POST {{Wrok.Identity.Api_HostAddress}}/auth/refresh-token/
Accept: application/json
Content-Type: application/json

{
  "token":""
}