@Wrok.Identity.Api_HostAddress = https://localhost:7062/identity
@Token = Bearer 

### Invite

POST {{ Wrok.Identity.Api_HostAddress }}/invitations
Authorization: {{Token}}
Accept: application/json
Content-Type: application/json

{
  "email": "test3@test.com",
  "role": "ProjectManager"
}

### Accept Invite
POST {{ Wrok.Identity.Api_HostAddress }}/invitations/iwVYs6+Kb9bDTg==/accept
Accept: application/json
Content-Type: application/json

{
  "email":"test4@test.com",
  "password":"Test1234*",
  "fullname":"Damian Project Manager",
  "tenantName":"TestTenant4"
}