@Wrok.Identity.Api_HostAddress = https://localhost:7010
@Token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjAxOTdlNmY4LWQzM2MtNzMyZS1hNzcwLTdlODAyMDFjYzdiMSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJUZXN0MiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InRlc3QyQHRlc3QuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJ0ZW5hbnQiOiIwMTk3ZTZmOC1kMzIxLTdlYzQtOTMyZC1iZGEzMzRjOTQyNDYiLCJleHAiOjE3NTIwOTgyNzUsImlzcyI6Ildyb2suSWRlbnRpdHkiLCJhdWQiOiJXcm9rLklkZW50aXR5In0.S0e-HiYU6YkX_iCTF5t7W8E-BxK44ymyYIPEbu5pbLc
### Invite

POST {{ Wrok.Identity.Api_HostAddress }}/invitations
Authorization: {{Token}}
Accept: application/json
Content-Type: application/json

{
  "email": "test3@test.com",
  "role": "ProjectManager"
}