@Wrok.Identity.Api_HostAddress = https://localhost:7062/identity

### GET ALL USERS
GET {{Wrok.Identity.Api_HostAddress}}/users
Accept: application/json
Authorization: Bearer 


### GET BY ID
GET {{Wrok.Identity.Api_HostAddress}}/users/0197e6f8-d33c-732e-a770-7e80201cc7b1
Accept: application/json
Authorization: Bearer 
