@Wrok.Identity.Api_HostAddress = https://localhost:7010

### GET ALL USERS
GET {{Wrok.Identity.Api_HostAddress}}/users
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjAxOTdlNmY4LWQzM2MtNzMyZS1hNzcwLTdlODAyMDFjYzdiMSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJUZXN0MiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InRlc3QyQHRlc3QuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJ0ZW5hbnQiOiIwMTk3ZTZmOC1kMzIxLTdlYzQtOTMyZC1iZGEzMzRjOTQyNDYiLCJleHAiOjE3NTIxNjM4MzksImlzcyI6Ildyb2suSWRlbnRpdHkiLCJhdWQiOiJXcm9rLklkZW50aXR5In0.j3ZEVD6EmNJ7Y6HsauAfrpveOaZRGwnbPjdFBINtER8


### GET BY ID
GET {{Wrok.Identity.Api_HostAddress}}/users/0197e6f8-d33c-732e-a770-7e80201cc7b1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjAxOTdlNmY4LWQzM2MtNzMyZS1hNzcwLTdlODAyMDFjYzdiMSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJUZXN0MiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InRlc3QyQHRlc3QuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJ0ZW5hbnQiOiIwMTk3ZTZmOC1kMzIxLTdlYzQtOTMyZC1iZGEzMzRjOTQyNDYiLCJleHAiOjE3NTIxNjM4MzksImlzcyI6Ildyb2suSWRlbnRpdHkiLCJhdWQiOiJXcm9rLklkZW50aXR5In0.j3ZEVD6EmNJ7Y6HsauAfrpveOaZRGwnbPjdFBINtER8
