// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wrok.Identity.Infrastructure.Data;

#nullable disable

namespace Wrok.Identity.Infrastructure.Data.Migrations
{
    [DbContext(typeof(WrokIdentityDbContext))]
    [Migration("20250709190547_InvitationsAdded")]
    partial class InvitationsAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wrok.Identity.Domain.Entities.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InvitedToTenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUserId")
                        .IsUnique();

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("InvitedToTenantId");

                    b.HasIndex("Email", "InvitedToTenantId")
                        .IsUnique();

                    b.ToTable("Invitations", (string)null);
                });

            modelBuilder.Entity("Wrok.Identity.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Wrok.Identity.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("Wrok.Identity.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasDiscriminator<string>("Role");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Wrok.Identity.Domain.Entities.AdminUser", b =>
                {
                    b.HasBaseType("Wrok.Identity.Domain.Entities.User");

                    b.Property<bool>("IsSuper")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedTenantAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasIndex("TenantId");

                    b.ToTable("Users", t =>
                        {
                            t.Property("JoinedTenantAt")
                                .HasColumnName("AdminUser_JoinedTenantAt");

                            t.Property("TenantId")
                                .HasColumnName("AdminUser_TenantId");
                        });

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("Wrok.Identity.Domain.Entities.FreelancerUser", b =>
                {
                    b.HasBaseType("Wrok.Identity.Domain.Entities.User");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Freelancer");
                });

            modelBuilder.Entity("Wrok.Identity.Domain.Entities.ProjectManagerUser", b =>
                {
                    b.HasBaseType("Wrok.Identity.Domain.Entities.User");

                    b.Property<DateTime>("JoinedTenantAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasIndex("TenantId");

                    b.HasDiscriminator().HasValue("ProjectManager");
                });

            modelBuilder.Entity("Wrok.Identity.Domain.Entities.Invitation", b =>
                {
                    b.HasOne("Wrok.Identity.Domain.Entities.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Wrok.Identity.Domain.Entities.User", "InvitedByUser")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wrok.Identity.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Invitations")
                        .HasForeignKey("InvitedToTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedUser");

                    b.Navigation("InvitedByUser");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Wrok.Identity.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Wrok.Identity.Domain.Entities.User", "User")
                        .WithOne("RefreshToken")
                        .HasForeignKey("Wrok.Identity.Domain.Entities.RefreshToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Wrok.Identity.Domain.Entities.AdminUser", b =>
                {
                    b.HasOne("Wrok.Identity.Domain.Entities.Tenant", "Tenant")
                        .WithMany("AdminUsers")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Wrok.Identity.Domain.Entities.ProjectManagerUser", b =>
                {
                    b.HasOne("Wrok.Identity.Domain.Entities.Tenant", "Tenant")
                        .WithMany("ProjectManagerUsers")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Wrok.Identity.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("AdminUsers");

                    b.Navigation("Invitations");

                    b.Navigation("ProjectManagerUsers");
                });

            modelBuilder.Entity("Wrok.Identity.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshToken");
                });
#pragma warning restore 612, 618
        }
    }
}
