@Wrok.Identity.Api_HostAddress = https://localhost:7010

### AUTH

POST {{Wrok.Identity.Api_HostAddress}}/auth/register/
Accept: application/json
Content-Type: application/json

{
  "email":"test@test.com",
  "password":"Test1234*",
  "fullname":"Test",
  "tenantName":"TestTenant"
}

###

POST {{Wrok.Identity.Api_HostAddress}}/auth/login/
Accept: application/json
Content-Type: application/json

{
  "email":"test@test.com",
  "password":"Test1234*"
}


### USERS

GET {{Wrok.Identity.Api_HostAddress}}/users
Accept: application/json

###

GET {{Wrok.Identity.Api_HostAddress}}/users?role=projectManager
Accept: application/json
