# Run when commits are pushed to main
on:
  workflow_dispatch:
  push:
    # Run when commits are pushed to mainline branch (main or master)
    # Set this to the mainline branch you are using
    branches:
      - main

# Set up permissions for deploying with secretless Azure federated credentials
# https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#set-up-azure-login-with-openid-connect-authentication
permissions:
  id-token: write
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
      AZURE_DB_USER: ${{ vars.AZURE_DB_USER }}
      AZURE_JWT_EXPIRATION_MINUTES: ${{ vars.AZURE_JWT_EXPIRATION_MINUTES }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install azd
        uses: Azure/setup-azd@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            8.x.x
            9.x.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release --verbosity normal

      - name: Testing .NET
        run: dotnet test --no-build --configuration Release --verbosity normal

      - name: Log in with Azure (Federated Credentials)
        run: |
          azd auth login `
            --client-id "$Env:AZURE_CLIENT_ID" `
            --federated-credential-provider "github" `
            --tenant-id "$Env:AZURE_TENANT_ID"
        shell: pwsh


      - name: Provision Infrastructure
        run: azd provision --no-prompt
        env:
          AZURE_DB_PASSWORD: ${{ secrets.AZURE_DB_PASSWORD }}
          AZURE_JWT_SECRET: ${{ secrets.AZURE_JWT_SECRET }}
          AZURE_MEDIATR_LICENSE: ${{ secrets.AZURE_MEDIATR_LICENSE }}

      - name: Deploy Application
        run: azd deploy --no-prompt
        env:
          AZURE_DB_PASSWORD: ${{ secrets.AZURE_DB_PASSWORD }}
          AZURE_JWT_SECRET: ${{ secrets.AZURE_JWT_SECRET }}
          AZURE_MEDIATR_LICENSE: ${{ secrets.AZURE_MEDIATR_LICENSE }}
        
